# Generated by Django 3.1.7 on 2021-05-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210413_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_10',
            field=models.TextField(default='asadf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='description_4',
            field=models.TextField(default='asdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='description_5',
            field=models.TextField(default='adf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='description_6',
            field=models.TextField(default='asdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='description_7',
            field=models.TextField(default='asdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='description_8',
            field=models.TextField(default='asdgasdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='description_9',
            field=models.TextField(default='asd'),
            preserve_default=False,
        ),
    ]
